name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      with:
        username: rikugun
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        DOCKER_PLATFORMS=linux/arm64,linux/amd64
        #docker login docker.pkg.github.com --username rikugun --password ${{ secrets.DOCKERHUB_TOKEN }}
        #docker buildx build --tag starmetal/nginx-rtmp:latest --platform ${DOCKER_PLATFORMS} --push .
        #docker build . --file Dockerfile --tag nginx-rtmp:latest
        #docker tag nginx-rtmp starmetal/nginx-rtmp:latest
        # docker login docker.pkg.github.com --username rikugun --password ${{ secrets.GITHUB_TOKEN }}
        # docker tag nginx-rtmp docker.pkg.github.com/starmetal/docker-nginx-rtmp/nginx-rtmp:latest
        # push docker.pkg.github.com/starmetal/docker-openencoder/nginx-rtmp:latest
        #build openeuler
        docker buildx build --file Dockerfile.openeuler --tag starmetal/nginx-rtmp:euler-latest --platform ${DOCKER_PLATFORMS} --push .

